# permissions for end users to edit zhapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zhapp-editor-role
rules:
- apiGroups:
  - apps.app.zhihu.com
  resources:
  - zhapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.app.zhihu.com
  resources:
  - zhapps/status
  verbs:
  - get
