# permissions for end users to view zhapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zhapp-viewer-role
rules:
- apiGroups:
  - apps.app.zhihu.com
  resources:
  - zhapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.app.zhihu.com
  resources:
  - zhapps/status
  verbs:
  - get
