apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cluster01-pd-node01
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    fsType: ext4
    path: /data1/sharedssd/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: shared-ssd-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cluster01-pd-node02
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    fsType: ext4
    path: /data1/sharedssd/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node02
  persistentVolumeReclaimPolicy: Retain
  storageClassName: shared-ssd-storage
  volumeMode: Filesystem
status:
  phase: Bound
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cluster01-pd-node03
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    fsType: ext4
    path: /data1/sharedssd/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node03
  persistentVolumeReclaimPolicy: Retain
  storageClassName: shared-ssd-storage
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cluster01-tidb-node01
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    fsType: ext4
    path: /data1/backup/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: backup-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cluster01-tidb-node02
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    fsType: ext4
    path: /data1/backup/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node02
  persistentVolumeReclaimPolicy: Retain
  storageClassName: backup-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cluster01-tidb-node03
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    fsType: ext4
    path: /data1/backup/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node03
  persistentVolumeReclaimPolicy: Retain
  storageClassName: backup-storage
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cluster01-tikv-node01
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    fsType: ext4
    path: /data1/ssd/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cluster01-tikv-node02
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    fsType: ext4
    path: /data1/ssd/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node02
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cluster01-tikv-node03
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    fsType: ext4
    path: /data1/ssd/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node03
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-storage
  volumeMode: Filesystem