apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-chaos-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-chaos-demo
  template:
    metadata:
      labels:
        app: nginx-chaos-demo
    spec:
      containers:
        - name: nginx-chaos-demo
          image: nginx:1.7.9