---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - repo.setting.zhihu.com
  resources:
  - repos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repo.setting.zhihu.com
  resources:
  - repos/status
  verbs:
  - get
  - patch
  - update
